[project]
name = "robonoha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "atproto>=0.0.68",
    "azure-functions>=2.1.0",
    "azure-identity>=1.25.3",
    "azure-keyvault-secrets>=4.11.0",
    "boto3>=1.43.29",
    "markovify>=0.9.4",
    "mecab>=0.996.13",
    "mecab-python3>=1.0.12",
    "python-dotenv>=1.2.2",
    "unidic-lite>=1.0.8",
]
